version: '3'

services:
  virtual_camera:
    container_name: virtual_camera
    build: virtual_camera/
    depends_on:
      - server
    networks:
      backend:
        ipv4_address: 172.18.0.3

  server:
    container_name: server
    build: server/
    ports:
      - "5000:5000"
    networks:
      backend:
        ipv4_address: 172.18.0.2

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
